### ISSUE TITLE
Rapid prototyping features, framework bootstrapping and security concerns.

### ISSUE THREAD

**Issue by patricknelson** [titledk/ttools-silverstripe#3]
I figured it'd make more sense to continue the thread started here in this repository: https://github.com/patricknelson/silverstripe-migrations/issues/3#issuecomment-104394056

Since it is relevant to features setup here. Basically I suggest setting up this module to facilitate incorporation of the SilverStripe framework and/or CMS code without having to be routed through a controller, but still satisfy these general requirements:
1. Stays secure by denying non-outsider access
2. Provides a simple interface for people to drop in their code without accidentally opening up their code to attack.

Maybe a structure similar to this (as I've not had time to review this module myself) but:
- User installs this module and it lives in root of site.
- Provide a `.gitignore`'ed directory which ignores everything except the `.gitignore` file, an `.htaccess` file and an `example.php` file, e.g. `ttools-silverstripe/workbench/`
- Inside this `example.php` file, provide the proper include states to include the proper file, e.g. `../lib/workbench-include.php`)

So, `ttools-silverstripe/workbench/example.php` can contain the following boilerplate: 

``` php
<?php
require_once("../lib/workbench-include.php");
// your rapidly prototyped code here

```

Make sense?

**Comment by anselmdk** [comment]
Actually most of this is taken care of already :)
As this is not a "normal" silverstripe module but at module for Terminal Tools for bootstrapping and facilitating SilverStripe development, see screenshot of my repository root.

My `.gitignore` then contains `ttools/workbench.php` to not add that into source.

Terminal Tools sets the repo structure up this opinionated way as I think that's the best way.

![screenshot 2015-05-21 21 36 13](https://cloud.githubusercontent.com/assets/1316533/7757312/99af4a8e-0001-11e5-8383-bf87af49f96a.png)
